# Generated by Django 4.1.3 on 2022-11-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='animal',
            fields=[
                ('animal_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('health', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'wildlife_db"."animal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('department_name', models.CharField(max_length=200)),
                ('department_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'public"."department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='email_id',
            fields=[
                ('email_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'wildlife_db"."email_id',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='expenditure',
            fields=[
                ('Item', models.CharField(max_length=200)),
                ('Invoice_ID', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'wildlife_db"."expenditure',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='mobile_no',
            fields=[
                ('mobile_number', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'wildlife_db"."mobile_no',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('Animal_Name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Disease', models.CharField(max_length=200)),
                ('History_of_illness', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'wildlife_db"."patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='preys_upon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'wildlife_db"."preys_upon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='price_list',
            fields=[
                ('Item', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'public"."price_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='sighted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'wildlife_db"."sighted',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Species_data',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('Remarks', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'wildlife_db"."species_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('emp_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nation', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=200)),
                ('District', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('Street', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'wildlife_db"."staff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='visited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'wildlife_db"."visited',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('nation', models.CharField(max_length=200)),
                ('citizen_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Gender', models.CharField(max_length=200)),
                ('State', models.CharField(max_length=200)),
                ('District', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'wildlife_db"."visitor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='wildlife_sanctuary',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('sanctuary_id', models.IntegerField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('weather', models.CharField(max_length=200)),
                ('wind_direction', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'wildlife_db"."wildlife_sanctuary',
                'managed': False,
            },
        ),
    ]
