# Generated by Django 4.1.3 on 2022-11-21 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='animal',
            table='animal',
        ),
        migrations.AlterModelTable(
            name='email_id',
            table='email_id',
        ),
        migrations.AlterModelTable(
            name='expenditure',
            table='expenditure',
        ),
        migrations.AlterModelTable(
            name='mobile_no',
            table='mobile_no',
        ),
        migrations.AlterModelTable(
            name='patient',
            table='patient',
        ),
        migrations.AlterModelTable(
            name='preys_upon',
            table='preys_upon',
        ),
        migrations.AlterModelTable(
            name='sighted',
            table='sighted',
        ),
        migrations.AlterModelTable(
            name='species_data',
            table='species_data',
        ),
        migrations.AlterModelTable(
            name='staff',
            table='staff',
        ),
        migrations.AlterModelTable(
            name='visited',
            table='visited',
        ),
        migrations.AlterModelTable(
            name='visitor',
            table='visitor',
        ),
        migrations.AlterModelTable(
            name='wildlife_sanctuary',
            table='wildlife_sanctuary',
        ),
    ]
